{% set version = "0.3.1" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-gutenbergr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/gutenbergr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/gutenbergr/gutenbergr_{{ version }}.tar.gz
  sha256: a26a932f0486a5d80963bcc7c030b940594cd39cf202e10ae5193ff44c33247f

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-cli
    - r-dplyr
    - r-glue
    - r-purrr
    - r-readmdtable
    - r-readr
    - r-rlang
    - r-stringr
    - r-tibble
    - r-urltools
  run:
    - r-base
    - r-cli
    - r-dplyr
    - r-glue
    - r-purrr
    - r-readmdtable
    - r-readr
    - r-rlang
    - r-stringr
    - r-tibble
    - r-urltools

test:
  commands:
    - $R -e "library('gutenbergr')"           # [not win]
    - "\"%R%\" -e \"library('gutenbergr')\""  # [win]

about:
  home: https://docs.ropensci.org/gutenbergr/, https://github.com/ropensci/gutenbergr
  license: GPL-2.0-only
  summary: Download and process public domain works in the Project Gutenberg collection <http://www.gutenberg.org/>. Includes metadata for all Project Gutenberg works, so that they can be searched and retrieved.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
    - hliebert
